name: my-go-app
replicas: 1
selflink: http://kube-download.poc.workisboring.com
image:
  repo: ghcr.io/techguys-tidc/kubectl-download
  tag: v1.0.0-alpha.3
service:
  port: 8080
ingress:
  host: kube-download.poc.workisboring.com


#ingress
classname: kong

config: |    
  {
      "clusters": [
        {
          "cluster": {
            "certificate-authority-data": "Meow",
            "server": "https://cluster1.example.com:6443"
          },
          "name": "cluster1"
        },
        {
          "cluster": {
            "certificate-authority-data": "Mewmew",
            "server": "https://cluster2.example.com:6443"
          },
          "name": "cluster2"
        },
        {
          "cluster": {
            "certificate-authority-data": "Maooo",
            "server": "https://cluster3.example.com:6443"
          },
          "name": "cluster3"
        }
      ],
      "users": [
        {
          "name": "oidc",
          "user": {
            "auth-provider": {
              "config": {
                "client-id": "client-k8s",
                "client-secret": "zi7k3S4j1by5adoPduPdJEP62t1B7Rhb",
                "idp-issuer-url": "https://login.poc.workisboring.com/realms/k8s",
                "id-token": "a",
                "refresh-token": "a"
              },
              "name": "oidc"
            }
          }
        }
      ]
    }


